mariadb:
  persistence:
    enabled: true
    size: 20Gi
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m
    limits:
      memory: 8Gi
      cpu: 4000m

rabbitmq:
  persistence:
    enabled: true
    size: 20Gi
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m

keystone:
  replicaCount: 2
  resources:
    requests:
      memory: 512Mi
      cpu: 500m

glance:
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
  persistence:
    enabled: true
    size: 50Gi
