apiVersion: v1
kind: Service
metadata:
  name: atmosphere
  namespace: openstack
spec:
  type: LoadBalancer
  selector:
    app: atmosphere
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
